HW11 for merge
Otus-DevOps-2022-02/sm0ke87_infra pull request #11
Opened 2022-04-26 18:56 UTC by sm0ke87

# Выполнено ДЗ №

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Изучен vagrant
 - Мытарства с molecule, версия подобрана ошибки не побеждены, так как использую python3.8

## Как запустить проект:
 - vagrant up

## Как проверить работоспособность:
 - http://<ip adress>:80

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2022-04-26 19:01 UTC, sm0ke87 commented
Молекула это какое-то издевательство, 2.7 версии в pip нет, методом перебора подобрал 2.18. Тесты не подхватились, но я все таки написал функцию в слепую(с вами научишься) используя is_listening. Да и сама молекула от 2 до 3 имеет оооочень сильные различия.
К красным тестам привык. Прошу принять.

2022-04-27 09:31 UTC, mrgreyves requested changes
Здравствуйте!)
В "красных" тестах проблема ни с молекулой
Предлагаю пофиксить все эти истории
Если посмотреть в тесты внимательно, то местами не хватает пустых строк в конце файлов, для пакера не хватает тестового ключа и прочие такие мелочи
Все таки стоит разок все это поправить
Думаю что не займет много времени

2022-05-04 09:03 UTC, sm0ke87 commented
Packer - исправлено!
Это даже не знаю, вроде все верно:
`find ansible/playbooks -name "*.yml" -type f -print0 | ANSIBLE_ROLES_PATH=ansible/roles xargs -0 -n1 ansible-playbook --syntax-check` exit_status should eq 0

Прошу принять

2022-05-04 09:36 UTC, mrgreyves approved these changes
Здравствуйте!)
Да, большая часть "мелочевки" пофикшена
ДЗ принимаю =)

2022-05-04 11:39 UTC, merged